//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.25 at 10:32:34 AM CEST 
//


package generate;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Beschrijft de boekenplank
 * 
 * <p>Java class for bookshelfType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bookshelfType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="categories">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="category" type="{http://www.prolector.org/schemas/books}categoryType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="books">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="book" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="subTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="isbn10" type="{http://www.prolector.org/schemas/books}isbn10Type"/>
 *                             &lt;element name="isbn13" type="{http://www.prolector.org/schemas/books}isbn13Type"/>
 *                             &lt;element name="language" type="{http://www.prolector.org/schemas/books}languageType"/>
 *                             &lt;element name="paperback" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="pageCount" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookshelfType", propOrder = {
    "categories",
    "books"
})
public class BookshelfType {

    @XmlElement(required = true)
    protected BookshelfType.Categories categories;
    @XmlElement(required = true)
    protected BookshelfType.Books books;

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link BookshelfType.Categories }
     *     
     */
    public BookshelfType.Categories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookshelfType.Categories }
     *     
     */
    public void setCategories(BookshelfType.Categories value) {
        this.categories = value;
    }

    /**
     * Gets the value of the books property.
     * 
     * @return
     *     possible object is
     *     {@link BookshelfType.Books }
     *     
     */
    public BookshelfType.Books getBooks() {
        return books;
    }

    /**
     * Sets the value of the books property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookshelfType.Books }
     *     
     */
    public void setBooks(BookshelfType.Books value) {
        this.books = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="book" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="subTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="isbn10" type="{http://www.prolector.org/schemas/books}isbn10Type"/>
     *                   &lt;element name="isbn13" type="{http://www.prolector.org/schemas/books}isbn13Type"/>
     *                   &lt;element name="language" type="{http://www.prolector.org/schemas/books}languageType"/>
     *                   &lt;element name="paperback" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="pageCount" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "book"
    })
    public static class Books {

        @XmlElement(required = true)
        protected List<BookshelfType.Books.Book> book;

        /**
         * Gets the value of the book property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the book property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBook().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BookshelfType.Books.Book }
         * 
         * 
         */
        public List<BookshelfType.Books.Book> getBook() {
            if (book == null) {
                book = new ArrayList<BookshelfType.Books.Book>();
            }
            return this.book;
        }


        /**
         * Beschrijft een boek
         * 
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="subTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="isbn10" type="{http://www.prolector.org/schemas/books}isbn10Type"/>
         *         &lt;element name="isbn13" type="{http://www.prolector.org/schemas/books}isbn13Type"/>
         *         &lt;element name="language" type="{http://www.prolector.org/schemas/books}languageType"/>
         *         &lt;element name="paperback" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="pageCount" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title",
            "subTitle",
            "isbn10",
            "isbn13",
            "language",
            "paperback",
            "pageCount",
            "publisher",
            "image",
            "weight"
        })
        public static class Book {

            @XmlElement(required = true)
            protected String title;
            protected String subTitle;
            @XmlElement(required = true)
            protected BigInteger isbn10;
            @XmlElement(required = true)
            protected String isbn13;
            @XmlElement(required = true)
            protected LanguageType language;
            protected boolean paperback;
            @XmlElement(required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger pageCount;
            @XmlElement(required = true)
            protected String publisher;
            @XmlElement(required = true)
            @XmlSchemaType(name = "anyURI")
            protected String image;
            protected double weight;

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the subTitle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubTitle() {
                return subTitle;
            }

            /**
             * Sets the value of the subTitle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubTitle(String value) {
                this.subTitle = value;
            }

            /**
             * Gets the value of the isbn10 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getIsbn10() {
                return isbn10;
            }

            /**
             * Sets the value of the isbn10 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setIsbn10(BigInteger value) {
                this.isbn10 = value;
            }

            /**
             * Gets the value of the isbn13 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsbn13() {
                return isbn13;
            }

            /**
             * Sets the value of the isbn13 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsbn13(String value) {
                this.isbn13 = value;
            }

            /**
             * Gets the value of the language property.
             * 
             * @return
             *     possible object is
             *     {@link LanguageType }
             *     
             */
            public LanguageType getLanguage() {
                return language;
            }

            /**
             * Sets the value of the language property.
             * 
             * @param value
             *     allowed object is
             *     {@link LanguageType }
             *     
             */
            public void setLanguage(LanguageType value) {
                this.language = value;
            }

            /**
             * Gets the value of the paperback property.
             * 
             */
            public boolean isPaperback() {
                return paperback;
            }

            /**
             * Sets the value of the paperback property.
             * 
             */
            public void setPaperback(boolean value) {
                this.paperback = value;
            }

            /**
             * Gets the value of the pageCount property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPageCount() {
                return pageCount;
            }

            /**
             * Sets the value of the pageCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPageCount(BigInteger value) {
                this.pageCount = value;
            }

            /**
             * Gets the value of the publisher property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPublisher() {
                return publisher;
            }

            /**
             * Sets the value of the publisher property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPublisher(String value) {
                this.publisher = value;
            }

            /**
             * Gets the value of the image property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImage() {
                return image;
            }

            /**
             * Sets the value of the image property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImage(String value) {
                this.image = value;
            }

            /**
             * Gets the value of the weight property.
             * 
             */
            public double getWeight() {
                return weight;
            }

            /**
             * Sets the value of the weight property.
             * 
             */
            public void setWeight(double value) {
                this.weight = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="category" type="{http://www.prolector.org/schemas/books}categoryType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "category"
    })
    public static class Categories {

        @XmlElement(required = true)
        protected List<CategoryType> category;

        /**
         * Gets the value of the category property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the category property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCategory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CategoryType }
         * 
         * 
         */
        public List<CategoryType> getCategory() {
            if (category == null) {
                category = new ArrayList<CategoryType>();
            }
            return this.category;
        }

    }

}
